

import { FormType, FormField } from './types';
import React from 'react';

export const ShieldIcon: React.FC<{ className?: string }> = ({ className }) => (
  <svg className={className} viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M24 4L6 12V26C6 34.8 13.2 42.4 24 44C34.8 42.4 42 34.8 42 26V12L24 4Z" fill="#1FA97C"/>
    <path d="M20 26L14 20L11 23L20 32L37 15L34 12L20 26Z" fill="white"/>
    <circle cx="35" cy="10" r="4" fill="#F9A825"/>
  </svg>
);

export const DocumentIcon: React.FC<{ className?: string }> = ({ className }) => (<svg xmlns="http://www.w3.org/2000/svg" className={className} viewBox="0 0 20 20" fill="currentColor"><path fillRule="evenodd" d="M4 4a2 2 0 012-2h4.586A2 2 0 0112 2.586L15.414 6A2 2 0 0116 7.414V16a2 2 0 01-2 2H6a2 2 0 01-2-2V4zm2 6a1 1 0 011-1h6a1 1 0 110 2H7a1 1 0 01-1-1zm1 3a1 1 0 100 2h6a1 1 0 100-2H7z" clipRule="evenodd" /></svg>);
export const VideoIcon: React.FC<{ className?: string }> = ({ className }) => (<svg xmlns="http://www.w3.org/2000/svg" className={className} viewBox="0 0 20 20" fill="currentColor"><path d="M2 6a2 2 0 012-2h6a2 2 0 012 2v8a2 2 0 01-2 2H4a2 2 0 01-2-2V6zm14.553 1.106A1 1 0 0016 8v4a1 1 0 00.553.894l2 1A1 1 0 0020 13V7a1 1 0 00-1.447-.894l-2 1z" /></svg>);
export const ImageIcon: React.FC<{ className?: string }> = ({ className }) => (<svg xmlns="http://www.w3.org/2000/svg" className={className} viewBox="0 0 20 20" fill="currentColor"><path fillRule="evenodd" d="M4 3a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V5a2 2 0 00-2-2H4zm12 12H4l4-8 3 6 2-4 3 6z" clipRule="evenodd" /></svg>);

export const SAFETY_MODULES: { title: FormType }[] = [
  { title: FormType.SafetyObservations },
  { title: FormType.InductionTraining },
  { title: FormType.DailyTrainingTalks },
  { title: FormType.FirstAidCases },
  { title: FormType.PEPTalks },
  { title: FormType.SpecialTechnicalTraining },
  { title: FormType.SafetyAdvisory },
  { title: FormType.StopWorkOrders },
  { title: FormType.Rectifications },
  { title: FormType.NearMissReports },
  { title: FormType.DangerousOccurrences },
  { title: FormType.SICMeetings },
  { title: FormType.GoodPractices },
  { title: FormType.Reports },
];

export const FORM_CONFIGS: Record<FormType, FormField[]> = {
  [FormType.SafetyObservations]: [
    { name: 'observationId', label: 'Observation ID', type: 'readonly' },
    { name: 'createdBy', label: 'Created By', type: 'readonly' },
    { name: 'project', label: 'Project', type: 'select', options: ['Project A', 'Project B', 'Project C'], required: true },
    { name: 'date', label: 'Date & Time', type: 'date', required: true },
    { name: 'beforePhoto', label: 'Before Photo', type: 'photo' },
    { name: 'afterPhoto', label: 'After Photo', type: 'photo' },
    { name: 'location', label: 'Location / Area', type: 'text', placeholder: 'Specific location where observed', required: true },
    { name: 'workActivity', label: 'Work Activity', type: 'text', placeholder: 'What work is being performed' },
    { name: 'department', label: 'Department', type: 'text', placeholder: 'Department or Section' },
    { name: 'shift', label: 'Shift', type: 'select', options: ['Day', 'Night'] },
    { name: 'observationType', label: 'Observation Type', type: 'select', options: ['Unsafe Act', 'Unsafe Condition'], required: true },
    { name: 'severityLevel', label: 'Severity Level', type: 'select', options: ['Safe', 'Medium', 'Critical'], required: true },
    { name: 'description', label: 'Detailed Description', type: 'textarea', placeholder: 'Describe what was observed...', required: true },
    { name: 'immediateCause', label: 'Immediate Cause', type: 'textarea', placeholder: 'What directly caused this condition / act?' },
    { name: 'rootCause', label: 'Root Cause', type: 'textarea', placeholder: 'Underlying reasons for the issue' },
    { name: 'ppeStatus', label: 'PPE Status', type: 'select', options: ['Compliant', 'Non-compliant'] },
    { name: 'likelihood', label: 'Likelihood', type: 'select', options: ['Low', 'Medium', 'High'] },
    { name: 'potentialConsequence', label: 'Potential Consequence', type: 'select', options: ['Minor', 'Moderate', 'Major'] },
    { name: 'correctiveActions', label: 'Corrective Actions', type: 'textarea', placeholder: 'Immediate actions taken', required: true },
    { name: 'recommendedCorrectiveActions', label: 'Recommended Corrective Actions', type: 'textarea', placeholder: 'What needs to be done...' },
    { name: 'responsiblePerson', label: 'Responsible Person', type: 'text', placeholder: 'Who is responsible?' },
    { name: 'targetCompletionDate', label: 'Target Completion Date', type: 'date' },
  ],
  [FormType.InductionTraining]: [
    { name: 'trainingId', label: 'Training ID', type: 'readonly' },
    { name: 'createdBy', label: 'Created By', type: 'readonly' },
    { name: 'project', label: 'Project', type: 'select', options: ['Project A', 'Project B'], required: true },
    { name: 'date', label: 'Date & Time', type: 'date', required: true },
    { name: 'photo', label: 'Photo', type: 'photo' },
    { name: 'contractorName', label: 'Contractor Name', type: 'text', required: true },
    { name: 'duration', label: 'Duration (Minutes)', type: 'number', required: true },
    { name: 'attendees', label: 'No. of attendees', type: 'number', required: true },
    { name: 'topicCovered', label: 'Topic Covered', type: 'textarea', required: true },
    { name: 'remarks', label: 'Remarks', type: 'textarea' },
  ],
  [FormType.DailyTrainingTalks]: [
    { name: 'talkId', label: 'Talk ID', type: 'readonly' },
    { name: 'createdBy', label: 'Created By', type: 'readonly' },
    { name: 'project', label: 'Project', type: 'select', options: ['Project A', 'Project B'], required: true },
    { name: 'date', label: 'Date & Time', type: 'date', required: true },
    { name: 'photo', label: 'Photo', type: 'photo' },
    { name: 'topic', label: 'Topic', type: 'text', required: true },
    { name: 'duration', label: 'Duration (Minutes)', type: 'number', required: true },
    { name: 'attendees', label: 'No. of attendees', type: 'number', required: true },
    { name: 'remarks', label: 'Remarks', type: 'textarea' },
  ],
  [FormType.PEPTalks]: [
    { name: 'talkId', label: 'Talk ID', type: 'readonly' },
    { name: 'createdBy', label: 'Created By', type: 'readonly' },
    { name: 'project', label: 'Project', type: 'select', options: ['Project A', 'Project B'], required: true },
    { name: 'date', label: 'Date & Time', type: 'date', required: true },
    { name: 'photo', label: 'Photo', type: 'photo' },
    { name: 'taskName', label: 'Task Name', type: 'text', required: true },
    { name: 'supervisor', label: 'Supervisor', type: 'text', required: true },
    { name: 'attendees', label: 'No. of attendees', type: 'number', required: true },
    { name: 'duration', label: 'Duration (Minutes)', type: 'number' },
    { name: 'hazardsIdentified', label: 'Hazards Identified', type: 'textarea', required: true },
    { name: 'controlMeasures', label: 'Control Measures', type: 'textarea', required: true },
    { name: 'location', label: 'Location', type: 'text', required: true },
    { name: 'remarks', label: 'Remarks', type: 'textarea' },
  ],
  [FormType.SpecialTechnicalTraining]: [
    { name: 'trainingId', label: 'Training ID', type: 'readonly' },
    { name: 'createdBy', label: 'Created By', type: 'readonly' },
    { name: 'project', label: 'Project', type: 'select', options: ['Project A', 'Project B'], required: true },
    { name: 'date', label: 'Date & Time', type: 'date', required: true },
    { name: 'photo', label: 'Photo', type: 'photo' },
    { name: 'trainingType', label: 'Training Type', type: 'text', placeholder: 'e.g., Height Work, Confined Space', required: true },
    { name: 'trainerName', label: 'Trainer Name', type: 'text', required: true },
    { name: 'contractorName', label: 'Contractor Name', type: 'text' },
    { name: 'attendees', label: 'No. of attendees', type: 'number', required: true },
    { name: 'duration', label: 'Duration (Minutes)', type: 'number' },
    { name: 'topicsCovered', label: 'Topics Covered', type: 'textarea', required: true },
    { name: 'remarks', label: 'Remarks', type: 'textarea' },
  ],
  [FormType.FirstAidCases]: [
    { name: 'caseId', label: 'Case ID', type: 'readonly' },
    { name: 'createdBy', label: 'Created By', type: 'readonly' },
    { name: 'project', label: 'Project', type: 'select', options: ['Project A', 'Project B'], required: true },
    { name: 'date', label: 'Date & Time', type: 'date', required: true },
    { name: 'photo', label: 'Photo', type: 'photo' },
    { name: 'injuredPersonName', label: 'Injured Person Name', type: 'text', required: true },
    { name: 'injuryType', label: 'Injury Type', type: 'text', required: true },
    { name: 'contractorName', label: 'Contractor Name', type: 'text' },
    { name: 'location', label: 'Location', type: 'text', required: true },
    { name: 'incidentDescription', label: 'Incident Description', type: 'textarea', required: true },
    { name: 'treatmentGiven', label: 'Treatment Given', type: 'textarea', required: true },
    { name: 'medicalDetails', label: 'Medical Details', type: 'textarea' },
    { name: 'treatedBy', label: 'Treated By', type: 'text', required: true },
    { name: 'referredToHospital', label: 'Referred to Hospital', type: 'select', options: ['Yes', 'No'] },
    { name: 'supervisorNotified', label: 'Supervisor Notified', type: 'select', options: ['Yes', 'No'] },
    { name: 'returnedToWork', label: 'Returned to Work', type: 'select', options: ['Yes', 'No'] },
    { name: 'followUpActions', label: 'Follow Up Actions', type: 'textarea' },
    { name: 'remarks', label: 'Remarks', type: 'textarea' },
  ],
  [FormType.SafetyAdvisory]: [
    { name: 'sawId', label: 'SAW ID', type: 'readonly' },
    { name: 'createdBy', label: 'Issued By', type: 'readonly' },
    { name: 'project', label: 'Project', type: 'select', options: ['Project A', 'Project B'], required: true },
    { name: 'date', label: 'Date & Time', type: 'date', required: true },
    { name: 'location', label: 'Location', type: 'text', required: true },
    { name: 'severityLevel', label: 'Severity Level', type: 'select', options: ['Low', 'Medium', 'High'], required: true },
    { name: 'warningDetails', label: 'Warning/Advisory Details', type: 'textarea', required: true },
    { name: 'correctiveActions', label: 'Required Corrective Actions', type: 'textarea', required: true },
    { name: 'issuedTo', label: 'Issued To (Individual/Team)', type: 'text', required: true },
    { name: 'photo', label: 'Photo', type: 'photo' },
  ],
  [FormType.StopWorkOrders]: [
    { name: 'swoId', label: 'SWO ID', type: 'readonly' },
    { name: 'createdBy', label: 'Issued By', type: 'readonly' },
    { name: 'project', label: 'Project', type: 'select', options: ['Project A', 'Project B'], required: true },
    { name: 'date', label: 'Date & Time of Stoppage', type: 'date', required: true },
    { name: 'location', label: 'Location of Halted Work', type: 'text', required: true },
    { name: 'reason', label: 'Reason for Stoppage (Unsafe Condition)', type: 'textarea', required: true },
    { name: 'correctiveActionRequired', label: 'Corrective Action Required to Resume', type: 'textarea', required: true },
    { name: 'authorizedBy', label: 'Authorized By', type: 'text', required: true },
    { name: 'photo', label: 'Photo', type: 'photo' },
  ],
  [FormType.Rectifications]: [
    { name: 'rectId', label: 'Rectification ID', type: 'readonly' },
    { name: 'observationId', label: 'Original Observation ID', type: 'text', placeholder: 'Enter ID of observation being rectified', required: true },
    { name: 'createdBy', label: 'Rectified By', type: 'readonly' },
    { name: 'project', label: 'Project', type: 'select', options: ['Project A', 'Project B'], required: true },
    { name: 'date', label: 'Date of Action', type: 'date', required: true },
    { name: 'actionTaken', label: 'Action Taken / Details of Closure', type: 'textarea', required: true },
    { name: 'status', label: 'Status', type: 'select', options: ['In Progress', 'Closed'], required: true },
    { name: 'photo', label: 'Photo Evidence', type: 'photo' },
  ],
  [FormType.NearMissReports]: [
    { name: 'nearMissId', label: 'Near Miss ID', type: 'readonly' },
    { name: 'createdBy', label: 'Reported By', type: 'readonly' },
    { name: 'project', label: 'Project', type: 'select', options: ['Project A', 'Project B'], required: true },
    { name: 'date', label: 'Date & Time of Incident', type: 'date', required: true },
    { name: 'location', label: 'Location', type: 'text', required: true },
    { name: 'description', label: 'Description of What Happened', type: 'textarea', required: true },
    { name: 'potentialConsequence', label: 'Potential Injury/Damage', type: 'textarea', placeholder: 'What could have happened?', required: true },
    { name: 'immediateAction', label: 'Immediate Action Taken', type: 'textarea' },
    { name: 'preventativeMeasures', label: 'Suggested Preventative Measures', type: 'textarea', required: true },
    { name: 'photo', label: 'Photo', type: 'photo' },
  ],
  [FormType.DangerousOccurrences]: [
    { name: 'doId', label: 'DO ID', type: 'readonly' },
    { name: 'createdBy', label: 'Reported By', type: 'readonly' },
    { name: 'project', label: 'Project', type: 'select', options: ['Project A', 'Project B'], required: true },
    { name: 'date', label: 'Date & Time of Occurrence', type: 'date', required: true },
    { name: 'location', label: 'Location', type: 'text', required: true },
    { name: 'description', label: 'Description of Major Incident', type: 'textarea', required: true },
    { name: 'consequence', label: 'Actual Consequence (if any)', type: 'textarea' },
    { name: 'emergencyResponse', label: 'Emergency Response Actions', type: 'textarea', required: true },
    { name: 'photo', label: 'Photo', type: 'photo' },
  ],
  [FormType.SICMeetings]: [
    { name: 'meetingId', label: 'Meeting ID', type: 'readonly' },
    { name: 'createdBy', label: 'Recorded By', type: 'readonly' },
    { name: 'project', label: 'Project', type: 'select', options: ['Project A', 'Project B'], required: true },
    { name: 'date', label: 'Date of Meeting', type: 'date', required: true },
    { name: 'attendees', label: 'Attendees (Site In-Charge, etc.)', type: 'textarea', required: true },
    { name: 'pointsDiscussed', label: 'Safety Points Discussed', type: 'textarea', required: true },
    { name: 'actionItems', label: 'Action Items and Responsibilities', type: 'textarea' },
  ],
  [FormType.GoodPractices]: [
    { name: 'gpId', label: 'GP ID', type: 'readonly' },
    { name: 'createdBy', label: 'Observed By', type: 'readonly' },
    { name: 'project', label: 'Project', type: 'select', options: ['Project A', 'Project B'], required: true },
    { name: 'date', label: 'Date Observed', type: 'date', required: true },
    { name: 'location', label: 'Location', type: 'text', required: true },
    { name: 'description', label: 'Description of Positive Practice/Innovation', type: 'textarea', required: true },
    { name: 'photo', label: 'Photo', type: 'photo' },
  ],
  [FormType.Reports]: [],
};